Create database Market

USE Market
CREATE TABLE PRODUCT
(
Id INT PRIMARY KEY IDENTITY(1,1),
Name NVARCHAR (50)
)

ALTER TABLE PRODUCT
ALTER COLUMN NAME NVARCHAR(30)

ALTER TABLE PRODUCT
ADD PRICE INT

INSERT INTO PRODUCT
VALUES
('IPHONE',23)

SELECT * FROM PRODUCT

SELECT Id,Name FROM PRODUCT

UPDATE PRODUCT
SET Name = 'PHONE'
WHERE Id = 1

INSERT INTO PRODUCT
VALUES
('NOTEBOOK', 120),
('NOTEBOOK1', 1200),
('NOTEBOOK2', 180),
('NOTEBOOK3', 220),
('NOTEBOOK4', 130),
('NOTEBOOK5', 320),
('NOTEBOOK6', 150),
('NOTEBOOK7', 520),
('NOTEBOOK8', 320),
('NOTEBOOK9', 160),
('NOTEBOOK0', 180),
('NOTEBOOK10', 800)

INSERT INTO PRODUCT
VALUES
('Car',30000)

SELECT * FROM PRODUCT
WHERE PRICE>10


SELECT * FROM PRODUCT
WHERE NAME LIKE '%A%'

SELECT * FROM PRODUCT
WHERE PRICE>100 AND PRICE<500

UPDATE PRODUCT
SET PRICE = 150
WHERE PRICE<150

SELECT * FROM PRODUCT

ALTER TABLE PRODUCT
ALTER COLUMN NAME NVARCHAR(50) NOT NULL

ALTER TABLE PRODUCT
ADD CONSTRAINT chk_name_length CHECK (LEN(NAME) >= 2);

INSERT INTO PRODUCT
VALUES
('QWE',23)


DELETE FROM PRODUCT
WHERE NAME = 'QWE'